# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Expose the HTTP API port
EXPOSE 3000

# Start the server
CMD ["npm", "start"]
